# Creates the ORCA top module file based on the netlist generated by SCAIE-V.
# For arguments, see maketop.py

import maketop

maketop.SCAIEV_CLK_SIGNAL = "sys_clk"
maketop.SCAIEV_RST_SIGNAL = "sys_rst"

def translate_pin_name(name):
    # Identity, since no conversion step is required.
    return name

maketop.write_top("CV32E40X_top_template.sv", "CV32E40X_top.sv", translate_pin_name)

